### ISSUE TITLE
Game should retain most recent score

### ISSUE THREAD

**Issue by phet-steele** [phetsims/fraction-matcher#98] opened 2016-03-31 18:29 UTC
The level selection screen needs to be changed to display stars for the most recent score achieved in a level. Currently the sim will always display the high score. Not a high priority issue, no need for a maintenance release. It's okay to wait until next re-deploy. See https://github.com/phetsims/balancing-act/issues/63 for the original issue.

**Comment by samreid** [comment] 2016-04-13 02:32
Unassigning until I'm (or someone else is) working on this sim again.

**Comment by jonathanolson** [comment] 2019-06-07 17:55
Based on https://github.com/phetsims/fractions-common/issues/92, I believe the high-score shown for levels is behaving correctly. @ariel-phet or @amanda-phet can you confirm?

**Comment by ariel-phet** [comment] 2019-06-08 03:07
@phet-steele can you check this?

**Comment by phet-steele** [comment] 2019-06-08 07:09
@ariel-phet @amanda-phet the game logic in 1.2.0-rc.1 is not working correctly (see at least phetsims/fractions-common/issues/104), so this is probably not ready to test.

What I did see was that the game did NOT show the most recent score; the game would continue to show the high score. 

@jonathanolson https://github.com/phetsims/fractions-common/issues/92 describes that the sim should not show time on the level select screen with a non-perfect score. It says nothing about showing high score vs. recent score. AFAIK, a summary of the desired game logic is:

Time - 

- Only record best time on a perfect score AND the time was faster than the previous best time (given one exists)

Level Select -

- Display the user's most recent attempt at a level whether it was a bad attempt or a perfect attempt.
- Only display best time under a level if the level is showing a perfect score. It would need to be possible that a time could be shown one moment, then hidden on the next attempt if it was not a perfect score.

@amanda-phet did I interpret this issue and https://github.com/phetsims/fractions-common/issues/92 correctly in my above summary? 1.2.0-rc.1 is currently failing all three of these points.

**Comment by jonathanolson** [comment] 2019-06-18 23:40
Patched in master and release branches. @phet-steele can you test master to see if this is fixed up?

There was a bug that meant after you got a perfect score, then the time would update to just be your last time (improper check).

I also created a separate Property for tracking what the displayed level-selection score should be, so that whenever you refresh a level OR visit it after completing, it resets to 0.

**Comment by jonathanolson** [comment] 2019-06-18 23:41
Also I'll want verification from @ariel-phet or @amanda-phet that the described/presenting behavior is the ideal.

**Comment by amanda-phet** [comment] 2019-06-19 16:32
The level selection screen seems to be behaving correctly- it only shows the most recent score, and only shows the best time if the most recent score was perfect. It's not the most perfect behavior IMO, because what makes the most sense to me is to eventually make a clear display showing both recent and best scores/times. But for this sim, right now, this is most consistent with the decisions we have made about game scoring. 

However, I noticed something odd in the dialog box. The first time I played, I got 12/12 and my time was  0:43. 

<img width="258" alt="Screen Shot 2019-06-19 at 10 26 58 AM" src="https://user-images.githubusercontent.com/7852916/59783325-258bd880-927d-11e9-96bd-95854a758bce.png">

Then I played again and got 11/12 and my time was 0:27. Of course that time is better, but the score is worse, so the design for the LSL just doesn't make sense anymore. 

<img width="265" alt="Screen Shot 2019-06-19 at 10 27 42 AM" src="https://user-images.githubusercontent.com/7852916/59783338-2d4b7d00-927d-11e9-8869-09036fe9125b.png">

I think we need a design meeting of some sort about this. Maybe I'm missing something, but I'm not sure it makes sense to show anything but the most recent score and most recent time on the LSL if this is the information in the dialog. @ariel-phet can we have a quick design meeting about this?

**Comment by jonathanolson** [comment] 2019-06-19 17:02
I may have caused a regression in the "best time" for the level complete dialog, checking.

**Comment by ariel-phet** [comment] 2019-06-20 02:48
@amanda-phet I am fine with a design meeting, probably next week, can you request it then?

@phet-steele being our game guru, do you have any thoughts here?

**Comment by amanda-phet** [comment] 2019-06-20 15:55
@ariel-phet I won't be available for design next week. I think it's just important that we have an in-person discussion about what is going on here and what needs to be done. It looks like we are all available Friday morning if that is ok.

**Comment by jonathanolson** [comment] 2019-06-20 18:57
I believe I just fixed the "best time" showing up when you get an imperfect score as part of https://github.com/phetsims/fractions-common/issues/104

**Comment by phet-steele** [comment] 2019-06-21 00:04
@ariel-phet @jonathanolson @amanda-phet Here's an initial stab. Just one of these three dialogs would appear given the described scenario for each. I think I covered all the scenarios?  All of these remove the space between "Score" and "Time", but maybe the space could still look fine there.

Getting a non-perfect score while there is no previous perfect score:


GREAT!
 :star::star:

Level: 1

Score: 11 out of 12
Time: 0:42

---
---

Either first time perfect score, or a better perfect score than one before (ie. better time):

Excellent!
 :star::star::star:

Level: 1

Score: 12 out of 12
Time: 0:24
(Your New Best!)

---
---

Non-perfect score with a previous perfect score (note how the time is faster than their best time), OR perfect score that is worse than the best:

GREAT!
 :star::star:

Level: 1

Score: 11 out of 12
Time: 0:16

Your Best
Score: 12 out of 12
Time: 0:24

---

I think the advantage of this last dialog is that is couples best time with perfect score, and should hopefully get the message across that best time is only recorded on a perfect score.

If this makes the dialog too long, I think we could survive dropping "Level: 1" from the dialog, or move it around, or make the spacing tighter (but no need to do any of this if it all fits well, IMO)

**Comment by phet-steele** [comment] 2019-06-21 00:11
Now that I've written all this up, I realize we can use the last dialog ANY time there is a new best. In other words, not necessarily link best time to a perfect score. We could have non-perfect scores still represent the player's best attempt and show something like:

Keep Trying
⭐️⭐️

Level: 1

Score: 4 out of 12
Time: 0:16

Your Best
Score: 10 out of 12
Time: 0:56

**Comment by ariel-phet** [comment] 2019-07-10 00:19
I think we made a decision awhile back to always show your "high score" on the LSS @amanda-phet since that is common practice. I also think the "best time" should only apply to a perfect score. 

There is certainly a conflict, where it is nice to see your best score, but it is also nice to know your most recent score. 

We have visited this issue many times, but I don't think it is worth changing for this game. We probably need to possibly rethink these things next time we make a new game, and perhaps revisit our general LSS approach, but now unfortunately I do not think is the appropriate time.

Closing this issue, since master seems to be following our current standard. 

Thanks for the input @phet-steele!

**Comment by ariel-phet** [comment] 2019-07-10 00:31
@phet-steele @amanda-phet sorry, wrote something incorrect and deleted it (if you get an email notification).

Looking back at the original issue (from balancing act) we had decided on most recent score to be displayed. So I agree, the sim should only be displaying a "best time" for a perfect score (which I believe is the current behavior). The sim should also display the most recent score (which it is not). Displaying the most recent score on the LSS should make the dialog and the LSS screen consistent.

Perhaps we could add a simple piece of logic. On the dialog, when the score is not perfect, just show your time. If the score is perfect, show your time and the best time. Does that sound like a good compromise @phet-steele @amanda-phet?

Would that be easy to implement @jonathanolson?

Either way, please adjust to most recent score on the LSS @jonathanolson

**Comment by phet-steele** [comment] 2019-07-10 01:05
> On the dialog, when the score is not perfect, just show your time. If the score is perfect, show your time and the best time. Does that sound like a good compromise @phet-steele @amanda-phet?

We all should have been looking at master. The sim does exactly that all ready; it just had many bugs before. 

https://phet-dev.colorado.edu/html/fraction-matcher/1.3.0-dev.2/phet/fraction-matcher_en_phet.html

@amanda-phet can you just review the link above (straight off master tonight)? I think it behaves according to my points in https://github.com/phetsims/fraction-matcher/issues/98#issuecomment-500102518 at least.

I guess we can save my new dialog suggestions for a different time ☹️.

**Comment by amanda-phet** [comment] 2019-07-10 17:47
The dialog looks correct to me now, along with the level selection screen.

**Closed by amanda-phet** 2019-07-10 17:47 UTC
Labels: design:polish, priority:2-high
